# Filtrage linéaire

In [2]:
# visionneuse externe interactive
#%matplotlib 

#imports
import numpy as np # tableaux
import scipy.ndimage as scp # correlation et convolution
import matplotlib.pyplot as plt # visionneur et tracés

import skimage
from skimage import color # gestion de la couleur
from skimage import data # petite banque d'images
from skimage import io # lecture et sauvegarde d'images
from skimage import util # conversions entier <-> flottants etc.
from skimage import filters as flt # filtres

# chemin d'accès à mes images 
my_path = "Images/Tmp/"

## Lissage simple (moyenne arithmétique)
(tester différentes largeurs de masque)

In [4]:
# Chargement de l'image et conversion éventuelle (gris, flottant)
I = data.coffee()
I = color.rgb2gray(I)

# Création du masque
w = 5 #largeur du masque
mask = ( np.array([1.0]*w**2) / w**2 ).reshape(w,w) # ou skimage.morphology.square(w)/w**2
print(mask)

# Convolution
J1 = scp.correlate(I, mask, mode='nearest') # voir ci-dessous pour le mode

# Affichage
plt.subplot(1,2,1)
plt.imshow(I, cmap='gray')

plt.subplot(1,2,2)
plt.imshow(J1, cmap='gray')

plt.show()

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


### Modes proposés dans skimage pour les bords
    
    
<table width=50% align=center>
<tr> 
<td>mode      <td>   Ext   <td>         Image          <td>   Ext
<!-----------+---------+------------------------+--------->
<tr>
<td>'mirror'   <td> 4  3  2 <td> 1  2  3  4  5  6  7  8 <td> 7  6  5
<tr>
<td>'reflect'  <td> 3  2  1 <td> 1  2  3  4  5  6  7  8 <td> 8  7  6
<tr>
<td>'nearest'  <td> 1  1  1 <td> 1  2  3  4  5  6  7  8 <td> 8  8  8
<tr>
<td>'constant' <td> 0  0  0 <td> 1  2  3  4  5  6  7  8 <td> 0  0  0
<tr>
<td>'wrap'     <td> 6  7  8 <td> 1  2  3  4  5  6  7  8 <td> 1  2  3
</table>

## Lissage gaussien
(tester différents écarts-types)

In [6]:
# Convolution
J2 = flt.gaussian(I, sigma=5) #  équivaut à J2 =  = flt.gaussian(I, sigma=1, mode='nearest')


# Affichage
plt.subplot(1,2,1)
plt.imshow(I, cmap='gray')

plt.subplot(1,2,2)
plt.imshow(J2, cmap='gray')

plt.show()

## Filtre passe-haut

In [ ]:
# On se propose de filtrer les caractères des touches de l'image 'keyb.png' 
I = 

# Filtrage passe-bas (utiliser un écart-type assez grand pour lisser les caractères avec le fond)
J = 

# Filtrage passe-haut (on récupère ce que le filtre passe-bas à supprimé)
K = 

# normalisation des valeurs (ici on recherche des détails clairs)
K[ K < 0 ] = 0 # (on ramène à 0 les pixels dont l'intensité est négative)

# Afficher I, J, K


## Rehaussement de contraste

In [ ]:
# Définir une fonction de rehaussement de contraste 
def enhance(img, sigma=0.5, iter=1):
    K = img
    for i in range(iter):
        K = K + (K - flt.gaussian(img, sigma=sigma))
        # ne pas oublier de normaliser les valeurs
        
    return K

# Appliquer sur une image avec différents paramètres



## Détection d'arêtes horizontale ou verticales
Fonctions `prewitt_h`, `prewitt_v` et `sobel_h`, `sobel_v` du module `filters`

In [ ]:
# Tester sur une image en niveau de gris
I = io.imread(my_path+"house.png")


# Affichage
plt.subplot(1,2,1)
plt.imshow(I, cmap='gray')

plt.subplot(1,2,2)
#plt.imshow(J2, cmap='gray')

plt.show()

## Gradient
Fonctions `prewitt` et `sobel` du module `filters`

In [ ]:
# Tester sur la même image que précédemment


## Laplacien
Fonction `laplace` du module `filters`

In [ ]:
# Tester sur la même image (penser à normaliser les valeurs)
